[package]
name = "comfort3d"
version = "0.0.1-alpha"
description = "My perfect little world."
license = "LICENSE"
homepage = "https://ch1tt0.github.io/comfort3d"
documentation = "https://ch1tt0.github.io/comfort3d/docs"
readme = "README.md"
publish = false
edition = "2024"

[dependencies]
avian3d = { version = "0.7.0", default-features = false, features = [ 
  "3d", 
  "default-collider", 
  "xpbd_joints", 
  "collider-from-mesh", 
  "bevy_scene", 
  "bevy_picking", 
  "parallel", 
  "simd", 
  "serialize", 
  "validate", 
  "f64", 
  "parry-f64",
  "bevy_diagnostic",
  "diagnostic_ui",
  "debug-plugin"
  ]}
bevy = { version = "0.19.1", features = [ "free_camera" ] }
serde = "1.0.229"
# WORK_AROUND: Work around for wasm-bindgen failing on:
# error: failed to find intrinsics to enable `clone_ref` function.
web-sys = "0.3.106"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

# Enable more optimization in the release profile at the cost of compile time.
[profile.release]
opt-level = 3
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "thin"
incremental = false

# Optimize for size in the wasm-release profile to reduce load times and bandwidth usage on web.
[profile.wasm-release]
# Default to release profile values.
inherits = "release"
# Optimize with size in mind (also try "z", sometimes it is better).
# Slightly slows compile times, great improvements to file size and runtime performance.
opt-level = "s"
# Strip all debugging information from the binary to slightly reduce file size.
strip = "debuginfo"
