[package]
name = "comfort-3d"
version = "0.0.1-alpha"
description = "My perfect little world."
license = "LICENSE"
homepage = "https://ch1tt0.github.io/comfort-3d"
documentation = "https://ch1tt0.github.io/comfort-3d/docs"
readme = "README.md"
publish = false
edition = "2024"

[dependencies]
avian3d = { version = "0.7.0", features = [ "simd", "serialize", "validate" ]}
bevy = "0.19.1"
serde = "1.0.229"
# WORK_AROUND: Work around for wasm-bindgen failing on:
# error: failed to find intrinsics to enable `clone_ref` function.
web-sys = "0.3.106"

[features]
dev = [
    "avian3d/bevy_diagnostic",
    "avian3d/diagnostic_ui",
    "avian3d/debug-plugin",

    "bevy/free_camera"
]

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

# Enable more optimization in the release profile at the cost of compile time.
[profile.release]
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "thin"

# Optimize for size in the wasm-release profile to reduce load times and bandwidth usage on web.
[profile.wasm-release]
# Default to release profile values.
inherits = "release"
# Optimize with size in mind (also try "z", sometimes it is better).
# Slightly slows compile times, great improvements to file size and runtime performance.
opt-level = "s"
# Strip all debugging information from the binary to slightly reduce file size.
strip = "debuginfo"
